events {}

http {
    upstream ledger_service {
        server ledger-service-app:3001;
    }

    upstream exchange_service {
        server exchange-service-app:3002;
    }

    server {
        listen 8080;

        location /api/ledger/ {
            proxy_pass http://ledger_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location /api/exchange/ {
            proxy_pass http://exchange_service/;
            proxy_set_header Host $host;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }

        location = /api/ledger {
            return 301 /api/ledger/;
        }

        location = /api/exchange {
            return 301 /api/exchange/;
        }

        # Fallback
        location / {
            return 404 "Not Found\n";
        }
    }
}